import { useCallback, useEffect, useMemo, useState } from 'react';
import { useTelaoSocket } from '../hooks/useTelaoSocket';
import { fetchStory, Story } from '../story';

function voterId(){const key='gambiarra-voter-id';let id=localStorage.getItem(key);if(!id){id=crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;localStorage.setItem(key,id)}return id}
export function StoryVoting(){
  const [story,setStory]=useState<Story|null>(null); const [votes,setVotes]=useState<Record<string,number>>({}); const [error,setError]=useState(''); const id=useMemo(voterId,[]);
  const reload=useCallback(async()=>{const next=await fetchStory();setStory(next);const chapter=next?.chapters[next.chapters.length-1];if(next?.status==='voting'&&chapter){const r=await fetch(`/api/votes/mine?roundId=${chapter.round.id}&voterId=${id}`);if(r.ok){const data=await r.json();setVotes(Object.fromEntries(data.map((v:any)=>[v.participantId,v.score])))}}},[id]);
  useEffect(()=>{reload();const timer=setInterval(reload,10000);return()=>clearInterval(timer)},[reload]);
  useTelaoSocket('story-voting',useCallback((m:any)=>{if(m.type==='story_state')setStory(m.story)},[]));
  const chapter=story?.chapters[story.chapters.length-1]; const responses=useMemo(()=>chapter?[...chapter.round.responses].sort((a,b)=>a.participantId.localeCompare(b.participantId)):[],[chapter]);
  const vote=async(participantId:string,score:number)=>{if(!chapter)return;setError('');const r=await fetch('/api/votes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({roundId:chapter.round.id,participantId,score,voterId:id,userAgent:navigator.userAgent})});if(r.ok)setVotes(old=>({...old,[participantId]:score}));else setError((await r.json().catch(()=>({}))).error||'Não foi possível votar')};
  if(!story||story.status!=='voting')return <main className="min-h-screen bg-slate-950 text-white grid place-items-center p-6"><div className="max-w-lg text-center"><p className="text-6xl">🗳️</p><h1 className="text-3xl font-black mt-5">Votação ainda não está aberta</h1><p className="text-slate-400 mt-3">Esta tela muda automaticamente quando as continuações estiverem prontas.</p></div></main>;
  return <main className="min-h-screen bg-slate-950 text-slate-100 p-5 lg:p-10"><header className="max-w-5xl mx-auto"><p className="text-amber-400 uppercase tracking-[.25em] text-xs">Capítulo {story.currentChapter} · voto comunitário</p><h1 className="text-4xl font-black mt-2">Qual continuação vira cânone?</h1><p className="text-slate-400 mt-3">Dê uma nota de 0 a 5 para cada texto. Considere coerência (40%), criatividade (35%) e estilo/humor (25%).</p></header><section className="max-w-5xl mx-auto mt-8 space-y-6">{responses.map((r,i)=><article key={r.participantId} className="bg-slate-900 border border-slate-800 rounded-3xl p-6 lg:p-8"><div className="flex justify-between"><p className="text-violet-300 uppercase tracking-widest text-xs">Continuação {i+1}</p>{votes[r.participantId]!==undefined&&<span className="text-emerald-300">Voto registrado: {votes[r.participantId]}</span>}</div><p className="whitespace-pre-wrap text-lg leading-relaxed mt-5">{r.content}</p><div className="flex flex-wrap gap-2 mt-7">{[0,1,2,3,4,5].map(score=><button key={score} onClick={()=>vote(r.participantId,score)} className={`w-12 h-12 rounded-xl font-black text-lg ${votes[r.participantId]===score?'bg-amber-400 text-slate-950':'bg-slate-800 hover:bg-slate-700'}`}>{score}</button>)}</div></article>)}{error&&<p className="text-red-300">{error}</p>}</section></main>
}
